spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallstreetwarriors
    username: postgres
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
